##############################################################
# compare_versions_gl.R
# Accuracy check for Gauss-Legendre quadrature integration.
#
# Tests whether GL integration recovers the same lambda values
# as the reference final_output.RDS (generated by the original
# midpoint-rule cluster script) for a stratified sample of rows.
#
# Reports convergence across n_gl = 20, 50, 100, 200, 500 and
# compares GL vs. midpoint vs. the historical reference.
#
# Usage: source("simulations/compare_versions/compare_versions_gl.R")
# from the project root.
##############################################################

# ============================================================
# 0. Guard and package load
# ============================================================
stopifnot(file.exists("DESCRIPTION"))
devtools::load_all()
library(tidyverse)


# ============================================================
# 1. Constants
# ============================================================
SIM_DIR      <- "simulations/covariates_perturbation"
DATA_DIR     <- readLines("_data.path")
REPLICATIONS <- 100L         # must match reference to get identical parameter draws
                              # (slice_sample RNG consumption depends on n)
PERTURBATION <- 0.01
MISSING_IDS  <- c(32794L, 33256L, 33257L, 171478L, 195665L, 201283L)
GL_SIZES     <- c(20L, 50L, 100L, 200L, 500L)
MIDPT_TOL    <- 1e-10        # expected tolerance for midpoint (from compare_versions.R)
GL_TOL       <- 1e-4         # acceptable GL deviation from reference


# ============================================================
# 2. Inline helpers (same as compare_versions.R)
# ============================================================
pars_to_list <- function(pars) {
  pars |>
    select(contains('.')) |>
    pivot_longer(cols = everything()) |>
    mutate(
      vr  = str_replace(name, '\\..*', ''),
      par = str_replace(name, paste0(vr, '.'), ''),
      vr  = case_match(vr, 'recruit' ~ 'rec', .default = vr)
    ) |>
    select(!name) |>
    group_split(vr) ->
  pars_l

  set_names(
    pars_l,
    pars_l |> map_chr(~.x$vr[1])
  ) |>
    map(~.x |> select(!vr) |> pivot_wider(names_from = par) |> unlist(use.names = TRUE))
}

# Midpoint-based empty mesh (matches original init_pop, N=0 path)
init_pop_midpt <- function(params, L = 127, h = 1) {
  Lmax <- round(params[["growth"]]["Lmax"], 0)
  m    <- length(seq(L, Lmax, h))
  msh  <- L + ((seq_len(m)) - 0.5) * h
  list(meshpts = msh, Nvec = rep(0, m), h = h, weights = rep(h, m))
}

# GL-based empty mesh using the same .gl_nodes_weights() used in the package
init_pop_gl <- function(params, L = 127, n_gl = 50L) {
  Lmax <- round(params[["growth"]]["Lmax"], 0)
  gl   <- .gl_nodes_weights(n_gl, a = L, b = Lmax)
  list(meshpts = gl$nodes, Nvec = rep(0.0, n_gl), h = NA_real_, weights = gl$weights)
}

# Bin DBH values onto nearest GL node (mirrors .stand_to_nvec() GL path)
dbh_to_sizeDist_gl <- function(dbh, N_gl) {
  msh        <- N_gl$meshpts
  bins       <- vapply(dbh, function(sz) which.min(abs(msh - sz)), integer(1L))
  N_out      <- N_gl
  N_out$Nvec <- tabulate(bins, nbins = length(msh)) * 1.0
  N_out
}

scale_vars <- function(value, cov, direction, range_dt = vars_rg) {
  cov_rg <- range_dt[[cov]]
  min_v  <- cov_rg[1]
  max_v  <- cov_rg[2]
  if (direction == 'scale')   return((value - min_v) / (max_v - min_v))
  if (direction == 'unscale') return(value * (max_v - min_v) + min_v)
  stop('`direction` must be "scale" or "unscale"')
}


# ============================================================
# 3. Load scaling ranges
# ============================================================
vars_rg <- append(
  setNames(readRDS(file.path(DATA_DIR, "climate_scaleRange.RDS")), c("temp", "prec")),
  list("dbh" = readRDS(file.path(SIM_DIR, "dbh_range.RDS")))
)


# ============================================================
# 4. Stratified row selection (same as compare_versions.R)
# ============================================================
selected_rows <- c(
  1L, 884L, 5000L, 22234L, 25000L, 31527L, 32448L,
  2266L, 22235L, 10000L, 22236L, 15000L, 31528L, 1963L, 20000L
)
stopifnot(!any(selected_rows %in% MISSING_IDS))
stopifnot(length(unique(selected_rows)) == length(selected_rows))


# ============================================================
# 5. Load big files once
# ============================================================
cat("Loading data files...\n")
sim_pars_all <- readRDS(file.path(SIM_DIR, "simulation_pars.RDS"))
pop_pars_all <- readRDS(file.path(SIM_DIR, "pop_pars.RDS"))
final_output <- readRDS(file.path(SIM_DIR, "final_output.RDS"))
cat("Data loaded.\n")

stopifnot(nrow(sim_pars_all) == 216027)

cat("Building final_output lookup table...\n")
fo_array_ids <- sapply(final_output, function(x) x$array_id[1])
fo_idx <- setNames(seq_along(fo_array_ids), fo_array_ids)
cat(sprintf("Lookup built: %d entries.\n", length(fo_idx)))

missing_in_fo <- selected_rows[!as.character(selected_rows) %in% names(fo_idx)]
if (length(missing_in_fo) > 0)
  stop(sprintf("Selected rows not in final_output: %s", paste(missing_in_fo, collapse = ", ")))
cat("All selected rows verified in final_output.\n\n")


# ============================================================
# 6. Per-row comparison function
#    Returns: reference lambda_base, midpoint lambda_base,
#             and GL lambda_base for each n_gl value.
# ============================================================
compare_row_gl <- function(array_id) {
  sim_pars  <- sim_pars_all[array_id, ]
  Sp        <- sim_pars$species_id
  plot_size <- sim_pars$plot_size
  temp_scl  <- scale_vars(sim_pars$bio_01_mean, "temp", "scale")
  prec_scl  <- scale_vars(sim_pars$bio_12_mean, "prec", "scale")

  set.seed(array_id)
  pop_pars <- pop_pars_all |>
    filter(species_id == Sp) |>
    select(!species_id) |>
    slice_sample(n = REPLICATIONS)

  plot_pars_list <- readRDS(file.path(SIM_DIR, "plot_parameters", paste0(Sp, ".RDS"))) |>
    filter(plot_id == sim_pars$plot_id, year_measured == sim_pars$year_measured) |>
    pull(plot_pars)
  plot_pars <- plot_pars_list[[1]]

  ref_output   <- final_output[[fo_idx[as.character(array_id)]]]
  ref_lambda   <- mean(ref_output$lambda_base, na.rm = TRUE)
  het_is_null  <- is.null(unlist(sim_pars$het_dbh))

  # --- Midpoint lambda (bin_w = 1, same as reference) ---
  midpt_lambdas <- numeric(REPLICATIONS)
  for (i in seq_len(REPLICATIONS)) {
    pars_i <- pars_to_list(pop_pars[i, ])
    re_i   <- plot_pars[i, ] |> unlist() |> unname()
    N_ref  <- init_pop_midpt(pars_i)
    N_con  <- dbh_to_sizeDist(dbh = unlist(sim_pars$con_dbh), N_intra = N_ref)
    N_het  <- if (het_is_null) N_ref else dbh_to_sizeDist(dbh = unlist(sim_pars$het_dbh), N_intra = N_ref)
    midpt_lambdas[i] <- max(getEigenValues(
      mkKernel(N_con, N_het, 1, plot_size, temp_scl, prec_scl, pars_i, re_i)$K
    ))
  }

  # --- GL lambda for each n_gl ---
  gl_lambdas <- setNames(
    lapply(GL_SIZES, function(n_gl) {
      lams <- numeric(REPLICATIONS)
      for (i in seq_len(REPLICATIONS)) {
        pars_i <- pars_to_list(pop_pars[i, ])
        re_i   <- plot_pars[i, ] |> unlist() |> unname()
        N_ref  <- init_pop_gl(pars_i, n_gl = n_gl)
        N_con  <- dbh_to_sizeDist_gl(dbh = unlist(sim_pars$con_dbh), N_gl = N_ref)
        N_het  <- if (het_is_null) N_ref else dbh_to_sizeDist_gl(dbh = unlist(sim_pars$het_dbh), N_gl = N_ref)
        lams[i] <- max(getEigenValues(
          mkKernel(N_con, N_het, 1, plot_size, temp_scl, prec_scl, pars_i, re_i)$K
        ))
      }
      mean(lams, na.rm = TRUE)
    }),
    paste0("gl_", GL_SIZES)
  )

  list(
    array_id     = array_id,
    species      = Sp,
    het_null     = het_is_null,
    ref_lambda   = ref_lambda,
    midpt_lambda = mean(midpt_lambdas, na.rm = TRUE),
    gl_lambdas   = gl_lambdas
  )
}


# ============================================================
# 7. Main execution
# ============================================================
cat(sprintf("Running GL accuracy check for %d rows × %d n_gl values × %d draws...\n\n",
            length(selected_rows), length(GL_SIZES), REPLICATIONS))

results <- lapply(selected_rows, function(id) {
  cat(sprintf("  Row %6d ... ", id))
  res <- tryCatch(
    compare_row_gl(id),
    error = function(e) {
      cat(sprintf("ERROR: %s\n", conditionMessage(e)))
      list(array_id = id, species = NA, het_null = NA,
           ref_lambda = NA, midpt_lambda = NA,
           gl_lambdas = setNames(as.list(rep(NA_real_, length(GL_SIZES))), paste0("gl_", GL_SIZES)))
    }
  )
  cat(sprintf("ref=%.4f  midpt=%.4f  gl_%d=%.4f\n",
              res$ref_lambda, res$midpt_lambda,
              GL_SIZES[length(GL_SIZES)], res$gl_lambdas[[paste0("gl_", GL_SIZES[length(GL_SIZES)])]]))
  res
})


# ============================================================
# 8. Summary tables
# ============================================================

# 8a. Convergence table: lambda values by method
cat("\n=== LAMBDA VALUES BY METHOD ===\n")
cat(sprintf("%-10s %-16s %10s %10s %s\n",
            "array_id", "species", "reference", "midpoint",
            paste(sprintf("GL(%d)", GL_SIZES), collapse = "  ")))
cat(strrep("-", 80), "\n")

for (r in results) {
  gl_vals <- sapply(paste0("gl_", GL_SIZES), function(k) r$gl_lambdas[[k]])
  cat(sprintf("%-10d %-16s %10.5f %10.5f  %s\n",
              r$array_id, r$species %||% "NA",
              r$ref_lambda %||% NA, r$midpt_lambda %||% NA,
              paste(sprintf("%8.5f", gl_vals), collapse = "  ")))
}

# 8b. Deviation from reference
cat("\n=== ABSOLUTE DEVIATION FROM REFERENCE (|GL - ref|) ===\n")
cat(sprintf("%-10s %-16s %10s %s\n",
            "array_id", "species", "midpt_dev",
            paste(sprintf("GL(%d)_dev", GL_SIZES), collapse = "  ")))
cat(strrep("-", 80), "\n")

for (r in results) {
  midpt_dev <- abs(r$midpt_lambda - r$ref_lambda)
  gl_devs   <- sapply(paste0("gl_", GL_SIZES), function(k) abs(r$gl_lambdas[[k]] - r$ref_lambda))
  cat(sprintf("%-10d %-16s %10.2e  %s\n",
              r$array_id, r$species %||% "NA",
              midpt_dev,
              paste(sprintf("%9.2e", gl_devs), collapse = "  ")))
}

# 8c. Convergence: GL(n) vs GL(max_n) — shows quadrature convergence independent of reference
cat(sprintf("\n=== GL CONVERGENCE: |GL(n) - GL(%d)| ===\n", GL_SIZES[length(GL_SIZES)]))
convergence_sizes <- GL_SIZES[-length(GL_SIZES)]
cat(sprintf("%-10s %-16s %s\n",
            "array_id", "species",
            paste(sprintf("GL(%d)", convergence_sizes), collapse = "  ")))
cat(strrep("-", 60), "\n")

for (r in results) {
  ref_gl  <- r$gl_lambdas[[paste0("gl_", GL_SIZES[length(GL_SIZES)])]]
  conv_devs <- sapply(paste0("gl_", convergence_sizes), function(k) abs(r$gl_lambdas[[k]] - ref_gl))
  cat(sprintf("%-10d %-16s %s\n",
              r$array_id, r$species %||% "NA",
              paste(sprintf("%8.2e", conv_devs), collapse = "  ")))
}

# 8d. Pass/fail summary
cat(sprintf("\n=== PASS/FAIL SUMMARY (GL tolerance: %g) ===\n", GL_TOL))
for (n_gl in GL_SIZES) {
  key    <- paste0("gl_", n_gl)
  devs   <- sapply(results, function(r) abs(r$gl_lambdas[[key]] - r$ref_lambda))
  n_pass <- sum(devs < GL_TOL, na.rm = TRUE)
  max_d  <- max(devs, na.rm = TRUE)
  cat(sprintf("  GL(%3d): %d/%d PASS  max_dev = %.2e\n",
              n_gl, n_pass, length(results), max_d))
}

midpt_devs <- sapply(results, function(r) abs(r$midpt_lambda - r$ref_lambda))
cat(sprintf("  midpt  : %d/%d PASS  max_dev = %.2e  (tol=%g)\n",
            sum(midpt_devs < MIDPT_TOL, na.rm = TRUE), length(results),
            max(midpt_devs, na.rm = TRUE), MIDPT_TOL))


# ============================================================
# 9. Benchmark: midpoint (h=1) vs GL(50, 100, 150)
#
# Runs for two species chosen to bracket the mesh-size range:
#   PINBAN — smallest fitted species (fewest midpoint bins)
#   QUERUB — largest fitted species (most midpoint bins)
# Uses the first non-missing row for each species in sim_pars_all.
# Times the full per-draw loop: mesh setup + mkKernel + getEigenValues.
# Runs BENCH_REPS outer iterations; reports median, min, max, and
# speedup relative to midpoint for that species.
# ============================================================
cat("\n=== TIMING BENCHMARK: midpoint (h=1) vs GL ===\n")

BENCH_REPS <- 30L
BENCH_GL   <- c(50L, 100L, 150L)
BENCH_SPS  <- c("PINBAN", "QUERUB")   # short-form species IDs (suffix match)

# Benchmark helper: time a no-argument function over n reps, return seconds
bench_fn <- function(fn, n = BENCH_REPS) {
  times <- numeric(n)
  for (i in seq_len(n)) {
    t0       <- proc.time()[["elapsed"]]
    fn()
    times[i] <- proc.time()[["elapsed"]] - t0
  }
  times
}

for (bench_sp_short in BENCH_SPS) {
  # Find first non-missing row whose species_id ends with bench_sp_short
  sp_rows <- which(endsWith(sim_pars_all$species_id, bench_sp_short) &
                   !seq_len(nrow(sim_pars_all)) %in% MISSING_IDS)
  if (length(sp_rows) == 0L) {
    cat(sprintf("\n  %s: no rows found — skipping\n", bench_sp_short))
    next
  }
  bench_row <- sp_rows[1L]
  bsim <- sim_pars_all[bench_row, ]
  bsp  <- bsim$species_id

  btemp <- scale_vars(bsim$bio_01_mean, "temp", "scale")
  bprec <- scale_vars(bsim$bio_12_mean, "prec", "scale")

  set.seed(bench_row)
  bpop <- pop_pars_all |>
    filter(species_id == bsp) |>
    select(!species_id) |>
    slice_sample(n = REPLICATIONS)

  bplot <- readRDS(file.path(SIM_DIR, "plot_parameters", paste0(bsp, ".RDS"))) |>
    filter(plot_id == bsim$plot_id, year_measured == bsim$year_measured) |>
    pull(plot_pars)
  bplot <- bplot[[1]]

  bpars    <- pars_to_list(bpop[1L, ])
  bre      <- bplot[1L, ] |> unlist() |> unname()
  bcon_dbh <- unlist(bsim$con_dbh)
  bhet_dbh <- unlist(bsim$het_dbh)

  # Midpoint mesh size for context
  N_ref_mp <- init_pop_midpt(bpars)
  n_midpt  <- length(N_ref_mp$meshpts)

  cat(sprintf("\n--- %s (row %d) --- midpoint bins: %d\n", bench_sp_short, bench_row, n_midpt))

  t_midpt <- bench_fn(function() {
    N_ref <- init_pop_midpt(bpars)
    N_con <- dbh_to_sizeDist(bcon_dbh, N_ref)
    N_het <- dbh_to_sizeDist(bhet_dbh, N_ref)
    getEigenValues(mkKernel(N_con, N_het, 1, bsim$plot_size, btemp, bprec, bpars, bre)$K)
  })

  t_gl <- lapply(BENCH_GL, function(n_gl) {
    bench_fn(function() {
      N_ref <- init_pop_gl(bpars, n_gl = n_gl)
      N_con <- dbh_to_sizeDist_gl(bcon_dbh, N_ref)
      N_het <- dbh_to_sizeDist_gl(bhet_dbh, N_ref)
      getEigenValues(mkKernel(N_con, N_het, 1, bsim$plot_size, btemp, bprec, bpars, bre)$K)
    })
  })

  cat(sprintf("%-14s %8s %8s %8s %10s\n", "method", "median_s", "min_s", "max_s", "speedup"))
  cat(strrep("-", 52), "\n")

  midpt_med <- median(t_midpt)
  cat(sprintf("%-14s %8.4f %8.4f %8.4f %10s\n",
              "midpoint(h=1)", midpt_med, min(t_midpt), max(t_midpt), "1.0x"))

  for (j in seq_along(BENCH_GL)) {
    med <- median(t_gl[[j]])
    cat(sprintf("%-14s %8.4f %8.4f %8.4f %9.1fx\n",
                sprintf("GL(%d)", BENCH_GL[j]),
                med, min(t_gl[[j]]), max(t_gl[[j]]),
                midpt_med / med))
  }
}
